# Generated by Django 5.1.15 on 2026-03-02 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_customuser_active_agent_access_jti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialVideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('quote', models.CharField(blank=True, default='', max_length=320)),
                ('source_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_video', models.FileField(blank=True, max_length=255, null=True, upload_to='video/masters')),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_in_hero', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testimonial_video_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='tva_active_priority_idx'), models.Index(fields=['show_in_hero', 'is_active', 'priority'], name='tva_hero_active_priority_idx')],
            },
        ),
    ]
