from django.urls import path
from . import views 

urlpatterns = [
    path('api/public/video-manifest', views.PublicVideoManifestView.as_view(), name='public-video-manifest'),
    path('api/public/video-manifest/', views.PublicVideoManifestView.as_view(), name='public-video-manifest-slash'),
    path('media/video/<path:file_name>', views.PublicVideoStreamView.as_view(), name='public-video-stream'),
    path('media/video/<path:file_name>/', views.PublicVideoStreamView.as_view(), name='public-video-stream-slash'),
    path('api/agent/videos', views.AgentVideoCollectionView.as_view(), name='agent-videos'),
    path('api/agent/videos/', views.AgentVideoCollectionView.as_view(), name='agent-videos-slash'),
    path('api/agent/videos/<int:video_id>', views.AgentVideoDetailView.as_view(), name='agent-video-detail'),
    path('api/agent/videos/<int:video_id>/', views.AgentVideoDetailView.as_view(), name='agent-video-detail-slash'),
    
    path('api/register',views.UserRegister.as_view(),name="user-register"),
    path('api/signup',views.UserSignupView.as_view(),name="user-signup"),
    path('api/signup/',views.UserSignupView.as_view(),name="user-signup-slash"),
    path('api/login',views.UserLoginView.as_view(),name="user-login"),
    path('api/agent/login',views.AgentAccessView.as_view(),name="agent-login-compat"),
    path('api/agent/login/',views.AgentAccessView.as_view(),name="agent-login-compat-slash"),
    path('api/agent/access',views.AgentAccessView.as_view(),name="agent-access"),
    path('api/agent/access/',views.AgentAccessView.as_view(),name="agent-access-slash"),
    path('api/agent/users',views.AgentUsersView.as_view(),name="agent-users"),
    path('api/agent/users/',views.AgentUsersView.as_view(),name="agent-users-slash"),
    path('api/agent/users/<str:user_id>',views.AgentUserDetailView.as_view(),name="agent-user-detail"),
    path('api/agent/users/<str:user_id>/',views.AgentUserDetailView.as_view(),name="agent-user-detail-slash"),
    path('api/chat/threads', views.ChatThreadsView.as_view(), name='chat-threads'),
    path('api/chat/threads/', views.ChatThreadsView.as_view(), name='chat-threads-slash'),
    path('api/chat/threads/<str:user_id>', views.ChatThreadManageView.as_view(), name='chat-thread-manage'),
    path('api/chat/threads/<str:user_id>/', views.ChatThreadManageView.as_view(), name='chat-thread-manage-slash'),
    path('api/chat/messages', views.ChatMessagesView.as_view(), name='chat-messages'),
    path('api/chat/messages/', views.ChatMessagesView.as_view(), name='chat-messages-slash'),
    path('api/chat/messages/<int:message_id>', views.ChatDeleteMessageView.as_view(), name='chat-message-delete'),
    path('api/chat/messages/<int:message_id>/', views.ChatDeleteMessageView.as_view(), name='chat-message-delete-slash'),
    path('api/chat/media', views.ChatMediaView.as_view(), name='chat-media'),
    path('api/chat/media/', views.ChatMediaView.as_view(), name='chat-media-slash'),
    path('api/chat/alias', views.ChatAliasView.as_view(), name='chat-alias'),
    path('api/chat/alias/', views.ChatAliasView.as_view(), name='chat-alias-slash'),
    path('api/chat/presence', views.ChatPresenceView.as_view(), name='chat-presence'),
    path('api/chat/presence/', views.ChatPresenceView.as_view(), name='chat-presence-slash'),
    path('api/announcements', views.UserAnnouncementsView.as_view(), name='user-announcements'),
    path('api/announcements/', views.UserAnnouncementsView.as_view(), name='user-announcements-slash'),
    path('api/agent/announcements', views.AgentAnnouncementCollectionView.as_view(), name='agent-announcements'),
    path('api/agent/announcements/', views.AgentAnnouncementCollectionView.as_view(), name='agent-announcements-slash'),
    path('api/agent/announcements/<int:announcement_id>', views.AgentAnnouncementDetailView.as_view(), name='agent-announcement-detail'),
    path('api/agent/announcements/<int:announcement_id>/', views.AgentAnnouncementDetailView.as_view(), name='agent-announcement-detail-slash'),
    path('api/community/personas', views.CommunityPersonaCollectionView.as_view(), name='community-personas'),
    path('api/community/personas/', views.CommunityPersonaCollectionView.as_view(), name='community-personas-slash'),
    path('api/community/ghost-members', views.CommunityPersonaCollectionView.as_view(), name='community-ghost-members'),
    path('api/community/ghost-members/', views.CommunityPersonaCollectionView.as_view(), name='community-ghost-members-slash'),
    path('api/community/personas/<int:persona_id>', views.CommunityPersonaDetailView.as_view(), name='community-persona-detail'),
    path('api/community/personas/<int:persona_id>/', views.CommunityPersonaDetailView.as_view(), name='community-persona-detail-slash'),
    path('api/community/ghost-members/<int:persona_id>', views.CommunityPersonaDetailView.as_view(), name='community-ghost-member-detail'),
    path('api/community/ghost-members/<int:persona_id>/', views.CommunityPersonaDetailView.as_view(), name='community-ghost-member-detail-slash'),
    path('api/community/feed', views.CommunityFeedView.as_view(), name='community-feed'),
    path('api/community/feed/', views.CommunityFeedView.as_view(), name='community-feed-slash'),
    path('api/community/settings', views.CommunitySettingsView.as_view(), name='community-settings'),
    path('api/community/settings/', views.CommunitySettingsView.as_view(), name='community-settings-slash'),
    path('api/ghost-chats/threads', views.GhostChatThreadsView.as_view(), name='ghost-chat-threads'),
    path('api/ghost-chats/threads/', views.GhostChatThreadsView.as_view(), name='ghost-chat-threads-slash'),
    path('api/ghost-chats/threads/from-community', views.GhostChatThreadFromCommunityView.as_view(), name='ghost-chat-thread-from-community'),
    path('api/ghost-chats/threads/from-community/', views.GhostChatThreadFromCommunityView.as_view(), name='ghost-chat-thread-from-community-slash'),
    path('api/ghost-chats/threads/<int:thread_id>', views.GhostChatThreadDetailView.as_view(), name='ghost-chat-thread-detail'),
    path('api/ghost-chats/threads/<int:thread_id>/', views.GhostChatThreadDetailView.as_view(), name='ghost-chat-thread-detail-slash'),
    path('api/ghost-chats/messages', views.GhostChatMessagesView.as_view(), name='ghost-chat-messages'),
    path('api/ghost-chats/messages/', views.GhostChatMessagesView.as_view(), name='ghost-chat-messages-slash'),
    path('api/ghost-chats/messages/<int:message_id>', views.GhostChatDeleteMessageView.as_view(), name='ghost-chat-message-delete'),
    path('api/ghost-chats/messages/<int:message_id>/', views.GhostChatDeleteMessageView.as_view(), name='ghost-chat-message-delete-slash'),
    path('api/agent/payments/global', views.AgentGlobalPaymentConfigView.as_view(), name='agent-global-payment'),
    path('api/agent/payments/global/', views.AgentGlobalPaymentConfigView.as_view(), name='agent-global-payment-slash'),
    path('api/agent/payments/global/<int:config_id>', views.AgentGlobalPaymentConfigDetailView.as_view(), name='agent-global-payment-detail'),
    path('api/agent/payments/global/<int:config_id>/', views.AgentGlobalPaymentConfigDetailView.as_view(), name='agent-global-payment-detail-slash'),
    path('api/payments/global/active', views.ActiveGlobalPaymentView.as_view(), name='active-global-payment'),
    path('api/payments/global/active/', views.ActiveGlobalPaymentView.as_view(), name='active-global-payment-slash'),
    path('api/agent/payments/templates', views.AgentPaymentTemplateCollectionView.as_view(), name='agent-payment-templates'),
    path('api/agent/payments/templates/', views.AgentPaymentTemplateCollectionView.as_view(), name='agent-payment-templates-slash'),
    path('api/agent/payments/templates/<int:template_id>', views.AgentPaymentTemplateDetailView.as_view(), name='agent-payment-template-detail'),
    path('api/agent/payments/templates/<int:template_id>/', views.AgentPaymentTemplateDetailView.as_view(), name='agent-payment-template-detail-slash'),
    path('api/payments/transactions', views.UserPaymentTransactionsView.as_view(), name='user-payment-transactions'),
    path('api/payments/transactions/', views.UserPaymentTransactionsView.as_view(), name='user-payment-transactions-slash'),
    path('api/agent/payments/transactions', views.AgentPaymentTransactionsView.as_view(), name='agent-payment-transactions'),
    path('api/agent/payments/transactions/', views.AgentPaymentTransactionsView.as_view(), name='agent-payment-transactions-slash'),
    path('api/agent/payments/transactions/<int:transaction_id>', views.AgentPaymentTransactionDetailView.as_view(), name='agent-payment-transaction-detail'),
    path('api/agent/payments/transactions/<int:transaction_id>/', views.AgentPaymentTransactionDetailView.as_view(), name='agent-payment-transaction-detail-slash'),
    path('api/agent/agreements/questions', views.AgentAgreementQuestionsView.as_view(), name='agent-agreement-questions'),
    path('api/agent/agreements/questions/', views.AgentAgreementQuestionsView.as_view(), name='agent-agreement-questions-slash'),
    path('api/agent/agreements/user-visibility', views.AgentAgreementUserVisibilityView.as_view(), name='agent-agreement-user-visibility'),
    path('api/agent/agreements/user-visibility/', views.AgentAgreementUserVisibilityView.as_view(), name='agent-agreement-user-visibility-slash'),
    path('api/agent/agreements/reset-user', views.AgentAgreementResetUserView.as_view(), name='agent-agreement-reset-user'),
    path('api/agent/agreements/reset-user/', views.AgentAgreementResetUserView.as_view(), name='agent-agreement-reset-user-slash'),
    path('api/agreements/questions', views.UserAgreementQuestionsView.as_view(), name='user-agreement-questions'),
    path('api/agreements/questions/', views.UserAgreementQuestionsView.as_view(), name='user-agreement-questions-slash'),
    path('api/agreements/answers', views.UserAgreementSubmitAnswersView.as_view(), name='user-agreement-answers'),
    path('api/agreements/answers/', views.UserAgreementSubmitAnswersView.as_view(), name='user-agreement-answers-slash'),
    path('api/agreements/complete', views.UserAgreementCompleteView.as_view(), name='user-agreement-complete'),
    path('api/agreements/complete/', views.UserAgreementCompleteView.as_view(), name='user-agreement-complete-slash'),
    path('api/logout',views.LogoutView.as_view(),name='user-logout'),
    path('api/token/refresh/', views.AgentTokenRefreshView.as_view(), name='token_refresh'),
    path('api/userprofile/', views.UserProfileView.as_view(), name='user-profile'),
    path('api/location/capture', views.UserLocationCaptureView.as_view(), name='user-location-capture'),
    path('api/location/capture/', views.UserLocationCaptureView.as_view(), name='user-location-capture-slash'),

   
]



